// <auto-generated />
namespace blackBox.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Phone_UserLoginProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Phone_UserLoginProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202305300419544_add_Phone_UserLoginProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
