// <auto-generated />
namespace blackBox.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addStockAvailtoColumn_Movies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStockAvailtoColumn_Movies));
        
        string IMigrationMetadata.Id
        {
            get { return "202306021403037_addStockAvailtoColumn_Movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
